import { Viga } from "next/font/google";
import "./globals.css";
import Footer from "./_components/Footer";
import Header from "./_components/Header";

const viga = Viga({ subsets: ["latin"], weight: "400"});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={viga.className}>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
